
	.definelabel oNaviStats_Attack, 0x1
	.definelabel oNaviStats_Speed, 0x2
	.definelabel oNaviStats_Charge, 0x3
	.definelabel oNaviStats_APwrAtk, 0x4
	.definelabel oNaviStats_BPwrAtk, 0x5
	.definelabel oNaviStats_FstBarr, 0x6
	.definelabel oNaviStats_BLeftAbility, 0x7
	.definelabel oNaviStats_CustomLevel, 0xa
	.definelabel oNaviStats_MegaLevel, 0xb
	.definelabel oNaviStats_GigaLevel, 0xc
	.definelabel oNaviStats_FloatShoes, 0x1b
	.definelabel oNaviStats_AirShoes, 0x1c
	.definelabel oNaviStats_UnderShirt, 0x1d
	.definelabel oNaviStats_SuperArmor, 0x23
	.definelabel oNaviStats_ChipShuffle, 0x60

	.definelabel GROUP_ACDC_TOWN, 0x0
	.definelabel MAP_ACDC_TOWN, 0x0

	.definelabel CS_VAR_IMM, 0xff
	
	.definelabel OW_UP, 0
	.definelabel OW_UP_RIGHT, 1
	.definelabel OW_RIGHT, 2
	.definelabel OW_DOWN_RIGHT, 3
	.definelabel OW_DOWN, 4
	.definelabel OW_DOWN_LEFT, 5
	.definelabel OW_LEFT, 6
	.definelabel OW_UP_LEFT, 7

	.definelabel EVENT_402, 0x402
	.definelabel EVENT_403_TALKED_TO_MODE_NPC, 0x403

	.definelabel EVENT_1900_NEVER_SET_IN_VANILLA, 0x1900
	.definelabel EVENT_TRIGGERED_OLD_SAVE, 0x1901

	.definelabel ITEM_TAGCHIP, 11
	.definelabel ITEM_REGUP1, 114

	.definelabel MAP_GROUP_TRANSITION_TYPE_SAME_MAP_GROUP_TYPE, 0x0
	.definelabel MAP_GROUP_TRANSITION_TYPE_INTERNET_TO_REAL_WORLD, 0x1
	.definelabel MAP_GROUP_TRANSITION_TYPE_REAL_WORLD_TO_INTERNET, 0x2

	.definelabel SPRITE_NPC_MEGA_MAN, 0x37
	.definelabel SPRITE_NPC_GREEN_NAVI, 0x3e
	.definelabel SPRITE_NPC_PINK_GIRL_NAVI, 0x45

	.definelabel SOUND_BEEP_64, 0x64
	.definelabel SOUND_TYPE, 0x65
	.definelabel SOUND_UNK_66, 0x66
	.definelabel SOUND_SELECT_67, 0x67
	.definelabel SOUND_UNSELECT_68, 0x68
	.definelabel SOUND_CANT_JACK_IN, 0x69
	.definelabel SOUND_BUSTER_6A, 0x6A
	.definelabel SOUND_HIT_6B, 0x6B
	.definelabel SOUND_DELETED, 0x6C
	.definelabel SOUND_HIT_6D, 0x6D
	.definelabel SOUND_HIT_6E, 0x6E
	.definelabel SOUND_HIT_BOMB_0, 0x6F
	.definelabel SOUND_HIT_BOMB_1, 0x70
	.definelabel SOUND_BUSTER_CHARGE, 0x71
	.definelabel SOUND_UNK_72, 0x72
	.definelabel SOUND_UNK_73, 0x73
	.definelabel SOUND_UNK_74, 0x74
	.definelabel SOUND_BEEP_75, 0x75
	.definelabel SOUND_LOG_OUT_76, 0x76
	.definelabel SOUND_LOG_IN_77, 0x77
	.definelabel SOUND_BATTLE_START, 0x78
	.definelabel SOUND_SELECT_79, 0x79
	.definelabel SOUND_SELECT_7A, 0x7A
	.definelabel SOUND_UNSELECT_7B, 0x7B
	.definelabel SOUND_UNSELECT_7C, 0x7C
	.definelabel SOUND_UNK_7D, 0x7D
	.definelabel SOUND_UNK_7E, 0x7E
	.definelabel SOUND_MENU_CUR_MOVE, 0x7F
	.definelabel SOUND_CUR_MOVE_80, 0x80
	.definelabel SOUND_MENU_SELECT, 0x81
	.definelabel SOUND_SELECT_82, 0x82
	.definelabel SOUND_EXIT_SUBMENU, 0x83
	.definelabel SOUND_LOW_HP, 0x84
	.definelabel SOUND_UNK_85, 0x85
	.definelabel SOUND_SELECT_86, 0x86
	.definelabel SOUND_HIT_87, 0x87
	.definelabel SOUND_UNK_88, 0x88
	.definelabel SOUND_UNK_89, 0x89
	.definelabel SOUND_UNK_8A, 0x8A
	.definelabel SOUND_OK_8B, 0x8B
	.definelabel SOUND_UNK_8C, 0x8C
	.definelabel SOUND_UNK_8D, 0x8D
	.definelabel SOUND_FADE_8E, 0x8E
	.definelabel SOUND_UNK_8F, 0x8F
	.definelabel SOUND_UNK_90, 0x90
	.definelabel SOUND_ERR_SELECT_91, 0x91
	.definelabel SOUND_CANNON_LAUNCH_AE, 0xAE
	.definelabel SOUND_EXPLOSION_C3, 0xc3
	.definelabel SOUND_FOLDER_EQUIP, 0x182

	.definelabel CANNON, 0x1
	.definelabel HICANNON, 0x2
	.definelabel M_CANNON, 0x3
	.definelabel AIRSHOT, 0x4
	.definelabel VULCAN1, 0x5
	.definelabel VULCAN2, 0x6
	.definelabel VULCAN3, 0x7
	.definelabel SUPRVULC, 0x8
	.definelabel SPREADR1, 0x9
	.definelabel SPREADR2, 0xa
	.definelabel SPREADR3, 0xb
	.definelabel TANKCAN1, 0xc
	.definelabel TANKCAN2, 0xd
	.definelabel TANKCAN3, 0xe
	.definelabel GUNDELS1, 0xf
	.definelabel GUNDELS2, 0x10
	.definelabel GUNDELS3, 0x11
	.definelabel YOYO, 0x13
	.definelabel FIREBRN1, 0x14
	.definelabel FIREBRN2, 0x15
	.definelabel FIREBRN3, 0x16
	.definelabel WIDESHT, 0x17
	.definelabel TRNARRW1, 0x18
	.definelabel TRNARRW2, 0x19
	.definelabel TRNARRW3, 0x1a
	.definelabel BBLSTAR1, 0x1b
	.definelabel BBLSTAR2, 0x1c
	.definelabel BBLSTAR3, 0x1d
	.definelabel THUNDER, 0x1e
	.definelabel DOLTHDR1, 0x1f
	.definelabel DOLTHDR2, 0x20
	.definelabel DOLTHDR3, 0x21
	.definelabel ELCPULS1, 0x22
	.definelabel ELCPULS2, 0x23
	.definelabel ELCPULS3, 0x24
	.definelabel RSKYHNY1, 0x25
	.definelabel RSKYHNY2, 0x26
	.definelabel RSKYHNY3, 0x27
	.definelabel RLNGLOG1, 0x28
	.definelabel RLNGLOG2, 0x29
	.definelabel RLNGLOG3, 0x2a
	.definelabel MACHGUN1, 0x2b
	.definelabel MACHGUN2, 0x2c
	.definelabel MACHGUN3, 0x2d
	.definelabel HEATDRGN, 0x2e
	.definelabel ELECDRGN, 0x2f
	.definelabel AQUADRGN, 0x30
	.definelabel WOODDRGN, 0x31
	.definelabel AIRHOCKY, 0x32
	.definelabel DRILARM, 0x33
	.definelabel TORNADO, 0x34
	.definelabel STATIC, 0x35
	.definelabel MINIBOMB, 0x36
	.definelabel ENERGBOM, 0x37
	.definelabel MEGENBOM, 0x38
	.definelabel FLSHBOM1, 0x39
	.definelabel FLSHBOM2, 0x3a
	.definelabel FLSHBOM3, 0x3b
	.definelabel BLKBOMB, 0x3c
	.definelabel AQUANDL1, 0x3d
	.definelabel AQUANDL2, 0x3e
	.definelabel AQUANDL3, 0x3f
	.definelabel CORNSHT1, 0x40
	.definelabel CORNSHT2, 0x41
	.definelabel CORNSHT3, 0x42
	.definelabel BUGBOMB, 0x43
	.definelabel GRASSEED, 0x44
	.definelabel ICESEED, 0x45
	.definelabel POISSEED, 0x46
	.definelabel SWORD, 0x47
	.definelabel WIDESWRD, 0x48
	.definelabel LONGSWRD, 0x49
	.definelabel WIDEBLDE, 0x4a
	.definelabel LONGBLDE, 0x4b
	.definelabel FIRESWRD, 0x4c
	.definelabel AQUASWRD, 0x4d
	.definelabel ELECSWRD, 0x4e
	.definelabel BAMBSWRD, 0x4f
	.definelabel WINDRACK, 0x50
	.definelabel STEPSWRD, 0x51
	.definelabel VARSWRD, 0x52
	.definelabel NEOVARI, 0x53
	.definelabel MOONBLD, 0x54
	.definelabel MURAMASA, 0x55
	.definelabel MCHNSWRD, 0x56
	.definelabel ELEMSWRD, 0x57
	.definelabel ASSNSWRD, 0x58
	.definelabel CRAKSHOT, 0x59
	.definelabel DUBLSHOT, 0x5a
	.definelabel TRPLSHOT, 0x5b
	.definelabel WAVEARM1, 0x5c
	.definelabel WAVEARM2, 0x5d
	.definelabel WAVEARM3, 0x5e
	.definelabel AURAHED1, 0x5f
	.definelabel AURAHED2, 0x60
	.definelabel AURAHED3, 0x61
	.definelabel LILBOLR1, 0x62
	.definelabel LILBOLR2, 0x63
	.definelabel LILBOLR3, 0x64
	.definelabel SANDWRM1, 0x65
	.definelabel SANDWRM2, 0x66
	.definelabel SANDWRM3, 0x67
	.definelabel AIRRAID1, 0x68
	.definelabel AIRRAID2, 0x69
	.definelabel AIRRAID3, 0x6a
	.definelabel FIREHIT1, 0x6b
	.definelabel FIREHIT2, 0x6c
	.definelabel FIREHIT3, 0x6d
	.definelabel BURNSQR1, 0x6e
	.definelabel BURNSQR2, 0x6f
	.definelabel BURNSQR3, 0x70
	.definelabel SENSOR1, 0x71
	.definelabel SENSOR2, 0x72
	.definelabel SENSOR3, 0x73
	.definelabel BOOMER, 0x74
	.definelabel HIBOOMER, 0x75
	.definelabel M_BOOMER, 0x76
	.definelabel LANCE, 0x77
	.definelabel GOLMHIT1, 0x78
	.definelabel GOLMHIT2, 0x79
	.definelabel GOLMHIT3, 0x7a
	.definelabel IRONSHL1, 0x7b
	.definelabel IRONSHL2, 0x7c
	.definelabel IRONSHL3, 0x7d
	.definelabel AIRSPIN1, 0x7e
	.definelabel AIRSPIN2, 0x7f
	.definelabel AIRSPIN3, 0x80
	.definelabel WIND, 0x81
	.definelabel FAN, 0x82
	.definelabel RFLECTR1, 0x83
	.definelabel RFLECTR2, 0x84
	.definelabel RFLECTR3, 0x85
	.definelabel SNAKE, 0x86
	.definelabel SUMNBLK1, 0x87
	.definelabel SUMNBLK2, 0x88
	.definelabel SUMNBLK3, 0x89
	.definelabel NUMBRBL, 0x8a
	.definelabel METEORS, 0x8b
	.definelabel JUSTCONE, 0x8c
	.definelabel MAGNUM, 0x8d
	.definelabel CIRCGUN, 0x8e
	.definelabel ROCKCUBE, 0x8f
	.definelabel TIMEBOM1, 0x90
	.definelabel MINE, 0x91
	.definelabel FANFARE, 0x92
	.definelabel DISCORD, 0x93
	.definelabel TIMPANI, 0x94
	.definelabel SILENCE, 0x95
	.definelabel VDOLL, 0x96
	.definelabel GUARDIAN, 0x97
	.definelabel ANUBIS, 0x98
	.definelabel RECOV10, 0x9a
	.definelabel RECOV30, 0x9b
	.definelabel RECOV50, 0x9c
	.definelabel RECOV80, 0x9d
	.definelabel RECOV120, 0x9e
	.definelabel RECOV150, 0x9f
	.definelabel RECOV200, 0xa0
	.definelabel RECOV300, 0xa1
	.definelabel PANLGRAB, 0xa2
	.definelabel AREAGRAB, 0xa3
	.definelabel GRABBNSH, 0xa4
	.definelabel GRABRVNG, 0xa5
	.definelabel PNLRETRN, 0xa6
	.definelabel GEDDON, 0xa7
	.definelabel HOLYPANL, 0xa8
	.definelabel SNCTUARY, 0xa9
	.definelabel COMINGRD, 0xaa
	.definelabel GOINGRD, 0xab
	.definelabel SLOGAUGE, 0xac
	.definelabel FSTGAUGE, 0xad
	.definelabel FULLCUST, 0xae
	.definelabel BUSTERUP, 0xaf
	.definelabel BUGFIX, 0xb0
	.definelabel INVISIBL, 0xb1
	.definelabel BARRIER, 0xb2
	.definelabel BARR100, 0xb3
	.definelabel BARR200, 0xb4
	.definelabel BBLWRAP, 0xb5
	.definelabel LIFEAUR, 0xb6
	.definelabel MAGCOIL, 0xb7
	.definelabel WHICAPSL, 0xb8
	.definelabel UNINSTLL, 0xb9
	.definelabel ANTINAVI, 0xba
	.definelabel ANTIDMG, 0xbb
	.definelabel ANTISWRD, 0xbc
	.definelabel ANTIRECV, 0xbd
	.definelabel COPYDMG, 0xbe
	.definelabel LIFESYNC, 0xbf
	.definelabel ATK_10, 0xc0
	.definelabel NAVI_20, 0xc1
	.definelabel COLORPT, 0xc2
	.definelabel ATK_30, 0xc3
	.definelabel DBLPOINT, 0xc4
	.definelabel ELEMTRAP, 0xc5
	.definelabel COLARMY, 0xc6
	.definelabel BLZRDBAL, 0xc7
	.definelabel TIMEBOM2, 0xc8
	.definelabel TIMEBOM3, 0xc9
	.definelabel BIGBOMB, 0xca
	.definelabel ROLL, 0xdd
	.definelabel ROLL2, 0xde
	.definelabel ROLL3, 0xdf
	.definelabel PROTOMAN, 0xe0
	.definelabel PROTOMNEX, 0xe1
	.definelabel PROTOMNSP, 0xe2
	.definelabel HEATMAN, 0xe3
	.definelabel HEATMANEX, 0xe4
	.definelabel HEATMANSP, 0xe5
	.definelabel ELECMAN, 0xe6
	.definelabel ELECMANEX, 0xe7
	.definelabel ELECMANSP, 0xe8
	.definelabel SLASHMAN, 0xe9
	.definelabel SLASHMNEX, 0xea
	.definelabel SLASHMNSP, 0xeb
	.definelabel ERASEMAN, 0xec
	.definelabel ERASEMNEX, 0xed
	.definelabel ERASEMNSP, 0xee
	.definelabel CHRGEMAN, 0xef
	.definelabel CHRGEMNEX, 0xf0
	.definelabel CHRGEMNSP, 0xf1
	.definelabel SPOUTMAN, 0xf2
	.definelabel SPOUTMNEX, 0xf3
	.definelabel SPOUTMNSP, 0xf4
	.definelabel TMHKMAN, 0xf5
	.definelabel TMHKMANEX, 0xf6
	.definelabel TMHKMANSP, 0xf7
	.definelabel TENGUMAN, 0xf8
	.definelabel TENGUMNEX, 0xf9
	.definelabel TENGUMNSP, 0xfa
	.definelabel GRNDMAN, 0xfb
	.definelabel GRNDMANEX, 0xfc
	.definelabel GRNDMANSP, 0xfd
	.definelabel DUSTMAN, 0xfe
	.definelabel DUSTMANEX, 0xff
	.definelabel DUSTMANSP, 0x100
	.definelabel BLASTMAN, 0x101
	.definelabel BLASTMNEX, 0x102
	.definelabel BLASTMNSP, 0x103
	.definelabel DIVEMAN, 0x104
	.definelabel DIVEMANEX, 0x105
	.definelabel DIVEMANSP, 0x106
	.definelabel CRCUSMAN, 0x107
	.definelabel CRCUSMNEX, 0x108
	.definelabel CRCUSMNSP, 0x109
	.definelabel JUDGEMAN, 0x10a
	.definelabel JUDGEMNEX, 0x10b
	.definelabel JUDGEMNSP, 0x10c
	.definelabel ELMNTMAN, 0x10d
	.definelabel ELMNTMNEX, 0x10e
	.definelabel ELMNTMNSP, 0x10f
	.definelabel COLONEL, 0x110
	.definelabel COLONELEX, 0x111
	.definelabel COLONELSP, 0x112
	.definelabel BASS, 0x12d
	.definelabel BIGHOOK, 0x12e
	.definelabel DELTARAY, 0x12f
	.definelabel COLFORCE, 0x130
	.definelabel BUGRSWRD, 0x131
	.definelabel BASSANLY, 0x132
	.definelabel METRKNUK, 0x133
	.definelabel CROSSDIV, 0x134
	.definelabel HUBBATC, 0x135
	.definelabel BGDTHTHD, 0x136
